# [custom.git-duet]
# command = "git config --list | grep duet.env.git | grep initials | awk -F '=' '{print $2}' | tr '\n' ' '"
# symbol = "🧑‍🤝‍🧑"
# when = """ test 1 -eq 1 """

[custom.xcode-select]
command = "xcode-select -print-path | cut -d '/' -f 3"
symbol = "🐥 "
when = """ ls | grep xcodeproj """
